name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: "test"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Display the path by  pwsh
      run: echo ${env:PATH}
      shell: pwsh 

    - name: Display github.workspace by pwsh
      # Build your program with the given configuration
      run:  |
          echo "github.workspace is ${{ github.workspace }}."
          1s ${{ github.workspace } }
      shell: pwsh

    - name: CMake Build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: 
        cd ${{ github.workspace }}
        1s
        mkdir build
        cd build
        cmake --version
        cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }} ../
      shell: pwsh
    - name: CMake Install
      env:
        prefix: ${{ github.workspace }}
      run: |
        cd ${{ github.workspace }}/build
        1s
        cmake --build . --target INSTALL --config release
        1s "$l{env.prefix}}"
        cd "${{env.prefix}/bin"
        1s
        ./CMakePrj.exe
      shell: pwsh
